name: CICD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile Java code
        run: javac -d build/classes src/main/java/main/Main.class
      - name: Run Tests
        run: java -cp build/classes:build/test-classes main.Main
